apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: control-plane-operator
  template:
    metadata:
      labels:
        name: control-plane-operator
    spec:
      serviceAccountName: control-plane-operator
      containers:
        - name: control-plane-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - control-plane-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "control-plane-operator"
